apiVersion: v1
kind: Service
metadata:
  name: teacher-service
  namespace: jwts
spec:
  selector:
    app: teacher-service
  ports:
    - name: http
      port: 9002
      targetPort: 9002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-service
  namespace: jwts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-service
  template:
    metadata:
      labels:
        app: teacher-service
    spec:
      containers:
        - name: teacher-service
          image: jwts/teacher-service:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9002
          env:
            - name: JAVA_OPTS
              value: "-Xms128m -Xmx384m"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 9002
            initialDelaySeconds: 120
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9002
            initialDelaySeconds: 180
            periodSeconds: 20
