server:
  port: 9003
spring:
  profiles:
    active: k8s
  application:
    name: course-service
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/jwts_db?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: EFZER
#    driver-class-name: com.mysql.jdbc.Driver
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
#    service-url:
#      defaultZone: http://127.0.0.1:8888/eureka
    instance:
      prefer-ip-address: true #使用ip地址向eureka server进行注册
      ease-renewal-interval-in-seconds: 5 #续约间隔时间
      lease-expiration-duration-in-seconds: 15 #续约到期时间
